spring:
  spark:
    other:
      'spark.sql.crossJoin.enabled': true
      'spark.executor.memory': 1G
      'spark.dynamicAllocation.minExecutors': 3
    app-name: streaming-test
  spark-streaming:
    duration: 3
